version: '3.8'

services:
  api:
    container_name: SchoolDoor-api-prod
    build: .
    ports:
      - "6001:6001"
    env_file:
      - env.prod
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    command: ["python", "run.py"]
