version: '3.8'

services:
  api:
    container_name: SchoolDoor-api-dev
    build: .
    ports:
      - "6001:6001"
    env_file:
      - env.dev
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - .:/app
    restart: unless-stopped
    command: ["python", "run.py"]
    working_dir: /app
